version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    env_file: "${ENV_FILE}"
    volumes:
      - ./config:/usr/src/app/config/:ro
      - ./scripts:/usr/src/app/scripts/:ro
      - ./server:/usr/src/app/server/:ro
      - ./.babelrc:/usr/src/app/.babelrc:ro
      - ./gulpfile.js:/usr/src/app/gulpfile.js:ro
      - ./nodemon.json:/usr/src/app/nodemon.json:ro
      - ./package.json:/usr/src/app/package.json:ro
    ports:
         - "3000:3000"
    links:
      - postgres
      - logspout
    command: npm run watch:server

  runner:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    env_file: "${ENV_FILE}"
    volumes_from:
      - api
    links:
      - postgres
      - api
    command: /bin/true
