#!/usr/bin/env bash

set -e

PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} -d ${POSTGRES_DB} <<-EOSQL
    ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_USER};
EOSQL
